name: ASP.NET Core CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Nuget pack
        run: ./scripts/deploy.sh dotnet-ci-example.csproj
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN_2: ${{ secrets.GITHUB_TOKEN_2 }}
